/**
 * ZIP Export Service
 * Bundles all color separation layers as individual EPS files
 * into a single downloadable ZIP archive.
 */

import JSZip from 'jszip';
import type { Layer, AdvancedConfig } from '../types';
import { layerToEPS, generateEPSFilename } from './epsExport';

/**
 * Export all visible layers as EPS files packaged in a ZIP.
 *
 * @param layers - Array of separation layers
 * @param config - Advanced config for DPI and size
 * @param jobName - Optional name for the ZIP file (defaults to "separations")
 */
export async function exportLayersAsEPS(
    layers: Layer[],
    config: AdvancedConfig,
    jobName: string = 'separations'
): Promise<void> {
    const zip = new JSZip();

    // Filter to visible layers only
    const visibleLayers = layers.filter(l => l.visible);

    if (visibleLayers.length === 0) {
        throw new Error('No visible layers to export.');
    }

    // Convert each layer to EPS and add to ZIP
    for (let i = 0; i < visibleLayers.length; i++) {
        const layer = visibleLayers[i];
        const epsBlob = layerToEPS(layer, config);
        const filename = generateEPSFilename(i + 1, layer.color.hex);
        zip.file(filename, epsBlob);
    }

    // Add a PRINT_INFO.txt with job metadata
    const printInfo = generatePrintInfo(visibleLayers, config);
    zip.file('PRINT_INFO.txt', printInfo);

    // Generate the ZIP and trigger download
    const zipBlob = await zip.generateAsync({
        type: 'blob',
        compression: 'DEFLATE',
        compressionOptions: { level: 6 }
    });

    triggerDownload(zipBlob, `${jobName}_EPS.zip`);
}

/**
 * Generate a human-readable print info file.
 */
function generatePrintInfo(layers: Layer[], config: AdvancedConfig): string {
    const lines = [
        '=== ScreenPrint Pro - EPS Export Info ===',
        '',
        `Date: ${new Date().toISOString()}`,
        `Resolution: ${config.outputDpi} DPI`,
        `Halftone LPI: ${config.halftoneLpi}`,
        `Halftone Type: ${config.halftoneType.toUpperCase()}`,
        `Separation Method: ${config.separationMethod}`,
        `Separation Type: ${config.separationType}`,
        '',
        '--- Channels ---',
    ];

    layers.forEach((layer, i) => {
        lines.push(`  ${String(i + 1).padStart(2, '0')}. Color: ${layer.color.hex.toUpperCase()} | File: ${generateEPSFilename(i + 1, layer.color.hex)}`);
    });

    lines.push('');
    lines.push('--- Notes ---');
    lines.push('Each EPS file is a Grayscale raster (Film Positive convention):');
    lines.push('  Black = Ink present');
    lines.push('  White = No ink (transparent/substrate)');
    lines.push('');
    lines.push('Compatible with: I-Image CTS, AccuRIP, FilmMaker, Wasatch SoftRIP');
    lines.push('');
    lines.push('Generated by ScreenPrint Pro - Antigravity');

    return lines.join('\n');
}

/**
 * Trigger a browser download for a Blob.
 */
function triggerDownload(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();

    // Cleanup
    setTimeout(() => {
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }, 100);
}
